'use client';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, Copy, Plus, Save, Trash2, Upload } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { assignmentTypes, emptyCandidate, type AssignmentCandidate, type ClassTime, type Course, type SavedAssignment } from '@/lib/studyflow/models';
import { analyzeSyllabus, duplicateIds, validateCandidate, type SyllabusAnalysis } from '@/lib/studyflow/parser';

const colors = ['#5c59c9', '#207b68', '#ac572c', '#d35d75', '#2b6cb0', '#7b5ea7'];

type Props = { onCancel: () => void; onSave: (course: Course, assignments: SavedAssignment[]) => void; initialCourse?: Course; initialAssignments?: SavedAssignment[] };

export function CourseBuilder({ onCancel, onSave, initialCourse, initialAssignments = [] }: Props) {
  const [step, setStep] = useState<'details' | 'assignments' | 'review' | 'confirm'>('details');
  const [name, setName] = useState(initialCourse?.name ?? '');
  const [code, setCode] = useState(initialCourse?.code ?? '');
  const [startDate, setStartDate] = useState(initialCourse?.startDate ?? '2026-09-28');
  const [endDate, setEndDate] = useState(initialCourse?.endDate ?? '2026-12-11');
  const [color, setColor] = useState(initialCourse?.color ?? colors[0]);
  const [classTimes, setClassTimes] = useState<ClassTime[]>(initialCourse?.classTimes ?? []);
  const [syllabus, setSyllabus] = useState('');
  const [rows, setRows] = useState<AssignmentCandidate[]>(initialAssignments);
  const [activeTab, setActiveTab] = useState('paste');
  const [error, setError] = useState('');
  const [analysis, setAnalysis] = useState<SyllabusAnalysis | null>(null);

  useEffect(() => {
    const warn = (event: BeforeUnloadEvent) => { if (name || syllabus || rows.length) event.preventDefault(); };
    window.addEventListener('beforeunload', warn);
    return () => window.removeEventListener('beforeunload', warn);
  }, [name, syllabus, rows.length]);

  const courseId = initialCourse?.id ?? 'course-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') + '-' + startDate;
  const duplicates = useMemo(() => duplicateIds(rows), [rows]);
  const updateRow = (id: string, patch: Partial<AssignmentCandidate>) => setRows(current => current.map(row => row.id === id ? { ...row, ...patch, validationIssues: validateCandidate({ ...row, ...patch }, startDate, endDate) } : row));
  const addRow = () => setRows(current => [...current, emptyCandidate(courseId)]);
  const extract = () => { const result = analyzeSyllabus(syllabus, courseId, startDate, endDate); setAnalysis(result); setRows(current => [...current.filter(row => row.source !== 'syllabus'), ...result.candidates]); };

  function continueDetails() {
    if (!name.trim() || !startDate || !endDate || startDate > endDate) { setError('Add a course name and a valid quarter date range.'); return; }
    setError(''); setStep('assignments');
  }
  function continueAssignments() {
    setRows(current => current.map(row => ({ ...row, validationIssues: validateCandidate(row, startDate, endDate) })));
    setStep('review');
  }
  function save() {
    const valid = rows.map(row => ({ ...row, validationIssues: validateCandidate(row, startDate, endDate) }));
    setRows(valid);
    const invalid = valid.filter(row => row.included && row.validationIssues.length);
    if (invalid.length) { setError(`${invalid.length} row${invalid.length === 1 ? '' : 's'} need attention before saving.`); return; }
    const course: Course = { id: courseId, name: name.trim(), code: code.trim(), color, startDate, endDate, classTimes };
    onSave(course, valid.filter(row => row.included).map(row => ({ ...row, courseId, reviewStatus: 'approved' })));
  }

  return <section className="panel course-builder" aria-labelledby="course-builder-title">
    <div className="builder-heading"><div><span className="eyebrow">BUILD YOUR QUARTER</span><h1 id="course-builder-title">{initialCourse ? 'Edit course' : 'Add a course'}</h1><p>{initialCourse ? 'Update course details while keeping its assignments and progress connected.' : 'Create the course first, then review every assignment before it reaches your calendar.'}</p></div><button className="text-button" onClick={onCancel}>Cancel</button></div>
    <div className="builder-steps" aria-label="Course setup steps"><span className={step === 'details' ? 'active' : 'complete'}>1 Course details</span><span className={step === 'assignments' ? 'active' : step === 'review' || step === 'confirm' ? 'complete' : ''}>2 Add assignments</span><span className={step === 'review' ? 'active' : step === 'confirm' ? 'complete' : ''}>3 Review assignments</span><span className={step === 'confirm' ? 'active' : ''}>4 Confirm & save</span></div>
    {error && <div className="builder-error" role="alert"><AlertTriangle size={17} />{error}</div>}
    {step === 'assignments' && <p className="builder-note"><strong>Paste entire syllabus.</strong> Whole-document analysis filters office hours, policies, holidays, and ordinary class dates before review.</p>}
    {analysis && step === 'assignments' && <div className="builder-note"><strong>Whole syllabus analyzed</strong><p>{analysis.candidates.length} likely assignments found · {analysis.readyCount} ready to review · {analysis.reviewCount} need confirmation · {analysis.ignoredCount} non-assignment dates ignored</p>{analysis.ignoredExamples.length > 0 && <details><summary>Why were some dates ignored?</summary>{analysis.ignoredExamples.map(item => <p key={item.line}>{item.reason}: {item.line}</p>)}</details>}</div>}
    {step === 'details' && <div className="builder-form">
      <div className="form-grid"><label>Course name *<input value={name} onChange={event => setName(event.target.value)} placeholder="Data Structures & Algorithms" /></label><label>Course code <input value={code} onChange={event => setCode(event.target.value)} placeholder="CSE 373" /></label><label>Quarter start date *<input type="date" value={startDate} onChange={event => setStartDate(event.target.value)} /></label><label>Quarter end date *<input type="date" value={endDate} onChange={event => setEndDate(event.target.value)} /></label></div>
      <fieldset className="color-picker"><legend>Course color *</legend><div className="color-options">{colors.map(option => <button type="button" aria-label={`Choose ${option}`} className={color === option ? 'selected' : ''} style={{ background: option }} key={option} onClick={() => setColor(option)}>{color === option && <Check size={16} />}</button>)}<label className="custom-color"><input type="color" value={color} onChange={event => setColor(event.target.value)} aria-label="Custom course color" /><span>Custom</span></label></div><p>Color is also paired with the course name or code wherever it appears.</p></fieldset>
      <section className="class-times"><div className="manual-entry-heading"><div><h2>Class Times</h2><p>Fixed commitments appear in the course color and help prevent future scheduling conflicts.</p></div><button className="secondary" onClick={() => setClassTimes(current => [...current, { id: `class-${Date.now()}`, courseId, label: 'Lecture', weekdays: [1, 3, 5], startTime: '10:30', endTime: '11:20', startDate, endDate, location: '', notes: '', online: false, recurrence: 'weekly' }])}><Plus size={15} />Add Class Time</button></div>{classTimes.map(pattern => <div className="class-time-row" key={pattern.id}><input aria-label="Class time label" value={pattern.label} onChange={event => setClassTimes(current => current.map(item => item.id === pattern.id ? { ...item, label: event.target.value } : item))} /><div className="weekday-picker">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((label, day) => <button type="button" className={pattern.weekdays.includes(day) ? 'selected' : ''} key={label} onClick={() => setClassTimes(current => current.map(item => item.id === pattern.id ? { ...item, weekdays: item.weekdays.includes(day) ? item.weekdays.filter(value => value !== day) : [...item.weekdays, day] } : item))}>{label}</button>)}</div><input aria-label="Class start time" type="time" value={pattern.startTime} onChange={event => setClassTimes(current => current.map(item => item.id === pattern.id ? { ...item, startTime: event.target.value } : item))} /><input aria-label="Class end time" type="time" value={pattern.endTime} onChange={event => setClassTimes(current => current.map(item => item.id === pattern.id ? { ...item, endTime: event.target.value } : item))} /><input aria-label="Class location" placeholder="Location" value={pattern.location} onChange={event => setClassTimes(current => current.map(item => item.id === pattern.id ? { ...item, location: event.target.value } : item))} /><button className="icon-button" aria-label="Delete class time" onClick={() => setClassTimes(current => current.filter(item => item.id !== pattern.id))}><Trash2 size={16} /></button></div>)}</section>
      <div className="builder-actions"><button className="primary" onClick={continueDetails}>Continue to assignments <Plus size={16} /></button></div>
    </div>}
    {step === 'assignments' && <div className="builder-form"><Tabs value={activeTab} onValueChange={setActiveTab}><TabsList aria-label="Assignment entry method"><TabsTrigger value="paste">Paste syllabus</TabsTrigger><TabsTrigger value="manual">Enter manually</TabsTrigger></TabsList></Tabs>{activeTab === 'paste' ? <div className="paste-panel"><label>Syllabus assignment section<textarea value={syllabus} onChange={event => setSyllabus(event.target.value)} placeholder={'Homework 1 - October 5 - 5%\nHomework 2 - October 19 - 5%\nMidterm - November 2 - 20%\nFinal Project - December 8 - 25%'} rows={9} /><span>Paste one assignment per line or paste a copied schedule table. Nothing is saved until you review it.</span></label><button className="secondary" onClick={extract}><Upload size={16} />Extract assignments</button>{!rows.filter(row => row.source === 'syllabus').length && syllabus && <div className="builder-note">We could not confidently find assignments in this text. Try the assignment schedule or important-dates section, or add assignments manually.<button className="secondary" onClick={() => { setActiveTab('manual'); addRow(); }}><Plus size={16} />Add assignment manually</button></div>}</div> : <div className="manual-entry"><div className="manual-entry-heading"><div><h2>Enter assignments manually</h2><p>Add one or several assignments before reviewing them together.</p></div><button className="primary" onClick={addRow}><Plus size={16} />Add Assignment</button></div>{!rows.filter(row => row.source === 'manual').length && <p className="builder-note">No manual assignments yet. Select Add Assignment to create an editable row.</p>}{rows.filter(row => row.source === 'manual').map(row => <ManualRow key={row.id} row={row} onChange={patch => updateRow(row.id, patch)} onDuplicate={() => setRows(current => [...current, { ...row, id: `${row.id}-copy` }])} onDelete={() => setRows(current => current.filter(item => item.id !== row.id))} />)}<button className="secondary" onClick={addRow}><Plus size={16} />Add Another Assignment</button></div>}<div className="builder-actions"><button className="text-button" onClick={() => setStep('details')}>Back</button><button className="primary" onClick={continueAssignments}>Continue to Review <Check size={16} /></button></div></div>}
    {step === 'review' && <div className="review-panel"><div className="review-toolbar"><div><h2>Review assignments</h2><p>{rows.length ? 'Correct uncertain rows, choose what to include, then continue to confirmation.' : 'No rows yet. Add one manually or go back to paste syllabus text.'}</p></div><button className="secondary" onClick={addRow}><Plus size={16} />Add Assignment Manually</button></div><div className="review-table-wrap"><table className="review-table"><thead><tr><th>Include</th><th>Assignment</th><th>Type</th><th>Release</th><th>Due date</th><th>Time</th><th>Est. minutes</th><th>Importance</th><th>Difficulty</th><th>Energy</th><th>Course Grade Weight (%)</th><th>Split into Study Sessions</th><th>Actions</th></tr></thead><tbody>{rows.map(row => <ReviewRow key={row.id} row={row} duplicate={duplicates.has(row.id)} onChange={patch => updateRow(row.id, patch)} onDuplicate={() => setRows(current => [...current, { ...row, id: `${row.id}-copy`, source: 'manual', rawText: '', sourceLine: '', sourceLineNumber: 0 }])} onDelete={() => setRows(current => current.filter(item => item.id !== row.id))} />)}</tbody></table></div><div className="builder-actions"><button className="text-button" onClick={() => setStep('assignments')}>Back</button><button className="primary" onClick={() => setStep('confirm')}>Continue to Confirm <Check size={16} /></button></div></div>}
    {step === 'confirm' && <div className="confirm-panel"><div className="brand-icon"><Save size={22} /></div><h2>Ready to save?</h2><p>{rows.filter(row => row.included).length} assignment{rows.filter(row => row.included).length === 1 ? '' : 's'} will be saved to {name}. Excluded rows and uncorrected rows will stay out of the calendar.</p><div className="builder-actions"><button className="text-button" onClick={() => setStep('review')}>Back to review</button><button className="primary" onClick={save}><Save size={16} />Save Course and Assignments</button></div></div>}
  </section>;
}

function ManualRow({ row, onChange, onDuplicate, onDelete }: { row: AssignmentCandidate; onChange: (patch: Partial<AssignmentCandidate>) => void; onDuplicate: () => void; onDelete: () => void }) {
  return <div className="manual-row"><label>Assignment title<input value={row.title} onChange={event => onChange({ title: event.target.value })} placeholder="Homework 1" /></label><label>Type<select value={row.type} onChange={event => onChange({ type: event.target.value as AssignmentCandidate['type'] })}>{assignmentTypes.map(type => <option key={type}>{type}</option>)}</select></label><label>Release date <span className="optional">optional</span><input type="date" value={row.releaseDate} onChange={event => onChange({ releaseDate: event.target.value })} /></label><label>Due date<input type="date" value={row.dueDate} onChange={event => onChange({ dueDate: event.target.value })} /></label><label>Due time<input type="time" value={row.dueTime} onChange={event => onChange({ dueTime: event.target.value })} /></label><label>Estimated time (minutes)<input type="number" min="1" value={row.estimatedMinutes} onChange={event => onChange({ estimatedMinutes: Number(event.target.value) || '' })} /></label><label>Energy<select value={row.energy} onChange={event => onChange({ energy: event.target.value as AssignmentCandidate['energy'] })}><option value="">Choose</option><option>Low</option><option>Medium</option><option>High</option></select></label><label>Importance (1–5)<select value={row.importance} onChange={event => onChange({ importance: Number(event.target.value) })}>{[1,2,3,4,5].map(value => <option key={value}>{value}</option>)}</select></label><label>Difficulty (1–5)<select value={row.difficulty} onChange={event => onChange({ difficulty: Number(event.target.value) })}>{[1,2,3,4,5].map(value => <option key={value}>{value}</option>)}</select></label><label>Course Grade Weight (%) <span className="optional">optional</span><input type="number" min="0" max="100" value={row.weight} onChange={event => onChange({ weight: event.target.value === '' ? '' : Number(event.target.value) })} /><small>How much this assignment contributes to your final course grade. Enter 20 for 20%. Leave blank if unspecified.</small></label><label className="check-label"><input type="checkbox" checked={row.divisible} onChange={event => onChange({ divisible: event.target.checked })} />Split into Study Sessions<small>Allows the planner to divide this work across days. It does not divide the grade weight.</small></label><div className="manual-row-actions"><button className="secondary" onClick={onDuplicate}><Copy size={15} />Duplicate</button><button className="icon-button" aria-label="Delete assignment" onClick={onDelete}><Trash2 size={16} /></button></div></div>;
}

function ReviewRow({ row, duplicate, onChange, onDuplicate, onDelete }: { row: AssignmentCandidate; duplicate: boolean; onChange: (patch: Partial<AssignmentCandidate>) => void; onDuplicate: () => void; onDelete: () => void }) {
  const issueText = [...row.validationIssues, ...(row.ambiguityFlags ?? []), ...(duplicate ? ['Possible duplicate: same title and due date.'] : [])];
  return <tr className={issueText.length ? 'needs-review' : 'complete'}><td><input aria-label="Include assignment" type="checkbox" checked={row.included} onChange={event => onChange({ included: event.target.checked })} /></td><td><input aria-label="Assignment title" value={row.title} onChange={event => onChange({ title: event.target.value })} />{row.sourceLine && <small title={row.sourceLine}>Source: {row.sourceLine}</small>}{issueText.map(issue => <span className="row-issue" key={issue}><AlertTriangle size={12} />{issue}</span>)}</td><td><select aria-label="Assignment type" value={row.type} onChange={event => onChange({ type: event.target.value as AssignmentCandidate['type'] })}>{assignmentTypes.map(type => <option key={type}>{type}</option>)}</select></td><td><input aria-label="Release date" type="date" value={row.releaseDate} onChange={event => onChange({ releaseDate: event.target.value })} /></td><td><input aria-label="Due date" type="date" value={row.dueDate} onChange={event => onChange({ dueDate: event.target.value })} /></td><td><input aria-label="Due time" type="time" value={row.dueTime} onChange={event => onChange({ dueTime: event.target.value })} /></td><td><input aria-label="Estimated minutes" type="number" min="1" value={row.estimatedMinutes} onChange={event => onChange({ estimatedMinutes: Number(event.target.value) || '' })} /></td><td><select aria-label="Importance" value={row.importance} onChange={event => onChange({ importance: Number(event.target.value) })}>{[1,2,3,4,5].map(value => <option key={value}>{value}</option>)}</select></td><td><select aria-label="Difficulty" value={row.difficulty} onChange={event => onChange({ difficulty: Number(event.target.value) })}>{[1,2,3,4,5].map(value => <option key={value}>{value}</option>)}</select></td><td><select aria-label="Energy level" value={row.energy} onChange={event => onChange({ energy: event.target.value as AssignmentCandidate['energy'] })}><option value="">Choose</option><option>Low</option><option>Medium</option><option>High</option></select></td><td><input aria-label="Course Grade Weight percentage" type="number" min="0" max="100" value={row.weight} onChange={event => onChange({ weight: event.target.value === '' ? '' : Number(event.target.value) })} /><small>% of final course grade</small></td><td><label className="check-label"><input aria-label="Split into Study Sessions" type="checkbox" checked={row.divisible} onChange={event => onChange({ divisible: event.target.checked })} />Split</label><small>Planner may divide study blocks.</small></td><td className="row-actions"><button aria-label="Duplicate assignment" onClick={onDuplicate}><Copy size={15} /></button><button aria-label="Delete assignment" onClick={onDelete}><Trash2 size={15} /></button></td></tr>;
}
